name: 游 Bug report
description: Reporta un problema en el proyecto
title: '[BUG] '
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar un bug 游뗿

  - type: input
    id: summary
    attributes:
      label: Descripci칩n breve
      description: Explica en una frase el bug
      placeholder: 'Ejemplo: El bot칩n de login no responde'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Explica c칩mo replicar el problema
      placeholder: |
        1. Ir a "..."
        2. Click en "..."
        3. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: 쯈u칠 deber칤a ocurrir?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Capturas de pantalla
      description: Si aplica, a침ade im치genes o v칤deos

  - type: dropdown
    id: severity
    attributes:
      label: Severidad
      options:
        - Baja
        - Media
        - Alta
    validations:
      required: true
